// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqIssaJHOVpu_TE94ctl7UWAjt-6fpek',
    appId: '1:975635414466:web:b6697203709e873bc1aa5b',
    messagingSenderId: '975635414466',
    projectId: 'appa-4bbcd',
    authDomain: 'appa-4bbcd.firebaseapp.com',
    storageBucket: 'appa-4bbcd.firebasestorage.app',
    measurementId: 'G-B6VEF95Y0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiUfnXDEhD6CKn8cYVUGHAsqdzlauQFbE',
    appId: '1:975635414466:android:c06c06672ac32c1cc1aa5b',
    messagingSenderId: '975635414466',
    projectId: 'appa-4bbcd',
    storageBucket: 'appa-4bbcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFBD07e3Ou8XnQ3eG4dYkIpgGPk5Mj-0',
    appId: '1:975635414466:ios:d03e4de5e33e236ec1aa5b',
    messagingSenderId: '975635414466',
    projectId: 'appa-4bbcd',
    storageBucket: 'appa-4bbcd.firebasestorage.app',
    iosBundleId: 'com.example.appa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSFBD07e3Ou8XnQ3eG4dYkIpgGPk5Mj-0',
    appId: '1:975635414466:ios:d03e4de5e33e236ec1aa5b',
    messagingSenderId: '975635414466',
    projectId: 'appa-4bbcd',
    storageBucket: 'appa-4bbcd.firebasestorage.app',
    iosBundleId: 'com.example.appa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVqIssaJHOVpu_TE94ctl7UWAjt-6fpek',
    appId: '1:975635414466:web:cf0b9278d6b105d1c1aa5b',
    messagingSenderId: '975635414466',
    projectId: 'appa-4bbcd',
    authDomain: 'appa-4bbcd.firebaseapp.com',
    storageBucket: 'appa-4bbcd.firebasestorage.app',
    measurementId: 'G-F68DE7F748',
  );

}